name: Build and Push API Image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+.dev[0-9]+"

jobs:
  build:
    uses: ./.github/workflows/generic-build-and-push.yml
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
